Define "progname" and use it in lieu of ${0}, i.e. invoked script path, for diagnostics

diff --git a/lib/jailer-util b/lib/jailer-util
--- a/lib/jailer-util
+++ b/lib/jailer-util
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 util::err() {
-  echo "${0}: ERROR: $1" >&2
+  echo "${progname}: ERROR: $1" >&2
   exit 1
 }
 
