Code cleanup, dry run, more colors, help menues
- A massive code cleanup
  many parts of the code has been redone, allowing the system to be more
  flexible for coming changes. Complex shell operations have been moved
  to simple if/else conditions

- Dry run
  Jailer now supports -D flag for the create subcommand to display all
  the changes it would do, such as the generated jail.conf file, ZFS
  commands, network commands and post-installation commands

- Colors
  More Shell colors has been added, such as Blue, Yello, Magenta, etc.

- Help menues
  All functions that have been redone now support the help
  sub-subcommand, which either prints a help menu or opens a man page
  (if available)

diff --git a/lib/jailer-core b/lib/jailer-core
--- a/lib/jailer-core
+++ b/lib/jailer-core
@@ -66,7 +66,7 @@ jail::info(){
       _hostname=$(jexec ${_jname} hostname)
       _jid=$(jls -j ${_jname} jid)
       _ipaddr=$(jexec ${_jname} ifconfig -f inet:dotted $(jexec ${_jname} ifconfig -g epair | head -1) | awk '/inet / {print $2}')
-      _gateway=$(jexec ${_jname} route -n get default 2>/dev/null | awk '/gateway/ {print $2}')
+      _gateway=$(jexec ${_jname} route -n get default 2>/dev/null | awk '/gateway/ {print $2; exit;}')
       _netmask=$(jexec ${_jname} ifconfig -f inet:dotted $(jexec ${_jname} ifconfig -g epair | head -1) | awk '/netmask/ {print $4}')
       _state="Active"
       _format="${_jformact}"
@@ -98,8 +98,8 @@ jail::start(){
   for _name in $@; do
     printf "Starting ${_name}: "
     service jail start ${_name} > /dev/null 2>&1
-    [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
-                 || (printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n")
+    jls -j ${_name} >/dev/null 2>&1 && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
+                 || (printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n") && return 1
   done
 }
 
@@ -107,17 +107,30 @@ jail::stop(){
   for _name in $@; do
     printf "Stopping ${_name}: "
     if (jls -j ${_name} > /dev/null 2>&1); then
-      service jail stop ${_name}
-      [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
-                   || (printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n")
+      if service jail stop ${_name} > /dev/null 2>&1 ; then
+        > /dev/null 2>&1 \
+        umount ${jailer_dir}/${_name}/dev
+        printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"
+      else
+        printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
+      fi
     else
-      printf "${COLOUR_SET_R}Failed! (is not an active jail)${COLOUR_END}\n"
+      printf "${COLOUR_SET_R}${_name} is not an active jail${COLOUR_END}\n"
     fi
   done
 }
 
 jail::destroy(){
-  local _name="$1"
+  local _name _opt
+
+  while getopts f _opt; do
+    case ${_opt} in
+      f) _force="-f" ;;
+    esac
+  done
+  shift $((OPTIND - 1))
+
+  _name="${1:-help}"
   [ ${_name} = "help" ] && help::destroy
 
   printf "Destroying ${_name}: "
@@ -129,18 +142,18 @@ jail::destroy(){
   if ! zfs list ${JAILER_ZFS_DATASET}/${_name} > /dev/null 2>&1; then
     printf "${COLOUR_SET_R}Failed! (does not exist)${COLOUR_END}\n"
   else
-    jail::_destroyzfs ${_name}
+    jail::_destroyzfs ${_name} ${_force}
 
     rm /etc/jail.conf.d/${_name}.conf > /dev/null 2>&1
-    sysrc jail_list-="${_name}"       > /dev/null 2>&1
     printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"
   fi
 }
 
 jail::_destroyzfs(){
   local _name="$1"
+  local _force="$2"
   sleep 1
-  zfs destroy -r ${JAILER_ZFS_DATASET}/${_name} || util::err "ZFS Destroy error, please check dataset dependency"
+  zfs destroy ${_force} -r ${JAILER_ZFS_DATASET}/${_name} || util::err "ZFS Destroy error, please check dataset dependency"
 }
 
 jail::image::extract(){
@@ -297,10 +310,13 @@ set_eb_vars(){
   exec.prestart  += "ifconfig epair\${id}a up descr vnet-\${name}";
   exec.prestart  += "ifconfig \${bridge} addm epair\${id}a up";
 
+  exec.start      = "/sbin/ifconfig lo0 127.0.0.1 up";
+  exec.start     += "/bin/sh /etc/rc";
+
+  exec.stop       = "/bin/sh /etc/rc.shutdown jail";
   exec.poststop   = "ifconfig \${bridge} deletem epair\${id}a";
   exec.poststop  += "ifconfig epair\${id}a destroy";
 
-  exec.start      = "/sbin/ifconfig lo0 127.0.0.1 up";
 EOF
 )
 }
@@ -311,6 +327,8 @@ set_os_vars(){
   _netvars=$(cat <<EOF
   interface       = \${bridge};
   ip4.addr        = ${_addr};
+  exec.start      = "/bin/sh /etc/rc";
+  exec.stop       = "/bin/sh /etc/rc.shutdown jail";
 EOF
 )
 }
@@ -320,9 +338,9 @@ jail::create(){
   local _version _snap
   local _vnet _addr _gw _netmask _resolver
   local _bridge _domain=${HOSTNAME}
-  local _silent
+  local _silent _dry_run _output
 
-  while getopts :a:b:c:d:e:f:g:m:nr:s:t: _opt; do
+  while getopts :a:b:c:d:e:f:g:m:nr:s:t:D _opt; do
     case ${_opt} in
       a) _addr="${OPTARG}" ;;
       b) _bridge="${OPTARG}" ;;
@@ -334,15 +352,20 @@ jail::create(){
       r) _version="${OPTARG}" ;;
       s) _snap="${OPTARG}" ;;
       t) _vnet="${OPTARG}" ;;
+      D) _dry_run="yes";;
       *) util::usage ;;
     esac
   done
   shift $((OPTIND - 1))
 
-  _name="${1:-$(uuidgen)}"
+  _name="${1:-$(uuidgen -r | cut -d '-' -f 5)}"
   _id=$(jail::get_next_id)
   _path=${jailer_dir}/${_name}
   _default_image=$(jailer image use 2>/dev/null)
+
+  [ "${_name}" = "help" ] && help::create
+  _output="/etc/jail.conf.d/${_name}.conf"
+  [ "${_dry_run}" = "yes" ] && _output="/dev/stdout"
 
   if [ -z "${_version}" ]; then
     if [ ! -z "${_default_image}" ]; then
@@ -370,7 +393,7 @@ jail::create(){
   then
     [ -z "${_addr}" ]    && _addr="dhcp"
     [ -z "${_bridge}" ]  && _bridge="bridge0"
-    [ -z "${_gw}" ]      && _gw=$(ifconfig -f inet:dotted ${_bridge} | awk '/inet/ {print $2}')
+    [ -z "${_gw}" ]      && _gw=$(ifconfig -f inet:dotted ${_bridge} | awk '/inet/ {print $2; exit;}')
     [ -z "${_netmask}" ] && _netmask=$(ifconfig -f inet:dotted ${_bridge} | awk '/inet/ {print $4; exit;}')
   fi
 
@@ -391,10 +414,14 @@ EOF
   esac
 
   # Creation begins ...
-  printf "Creating ${_name}: "
+  if [ "${_dry_run}" = "yes" ]; then
+    printf "${COLOUR_SET_B}jail.conf file =>${COLOUR_END}\n"
+  else
+    printf "Creating ${_name}: "
+  fi
 
   # Generate the configuration file
-  cat << EOF > /etc/jail.conf.d/${_name}.conf
+  cat << EOF > $_output
 # vim: set syntax=sh:
 exec.clean;
 allow.raw_sockets;
@@ -406,7 +433,6 @@ ${_devfsvars}
   \$bridge         = "${_bridge}";
   \$domain         = "${_domain}";
 ${_netvars}
-  exec.start     += "/bin/sh /etc/rc";
 
   host.hostname   = "\${name}.\${domain}";
   path            = "${_path}";
@@ -415,47 +441,99 @@ ${_netvars}
 }
 EOF
 
-  # ZFS send / recv
+  # ZFS
   if [ ! -z ${_snap} ]; then
-    (zfs send ${JAILER_ZFS_DATASET}/${_snap} |
-     zfs recv ${JAILER_ZFS_DATASET}/${_name})
+    _zfscmd="
+  (zfs send ${JAILER_ZFS_DATASET}/${_snap} |
+   zfs recv ${JAILER_ZFS_DATASET}/${_name})
+    "
   else
-    (zfs send ${JAILER_ZFS_DATASET}/image/${_version}@base |
-     zfs recv ${JAILER_ZFS_DATASET}/${_name})
+    _zfscmd="
+  (zfs send ${JAILER_ZFS_DATASET}/image/${_version}@base |
+   zfs recv ${JAILER_ZFS_DATASET}/${_name})
+    "
+  fi
+  if [  "${_dry_run}" != "yes" ]; then
+    eval "${_zfscmd}"
+  else
+    printf "${COLOUR_SET_B}ZFS commands =>${COLOUR_END}\n"
+    echo "${_zfscmd}"
   fi
 
   # Set the resolver
   if [ ! -z ${_resolver} ]; then
-    echo "nameserver ${_resolver}" > "${_path}/etc/resolv.conf"
+    _resolvcmd=$(cat <<EOF
+  echo "nameserver ${_resolver}" > "${_path}/etc/resolv.conf"
+EOF
+)
   else
-    cp /etc/resolv.conf "${_path}/etc/resolv.conf"
+    _resolvcmd=$(cat <<EOF
+  cp /etc/resolv.conf "${_path}/etc/resolv.conf"
+EOF
+)
+  fi
+  if [ "${_dry_run}" != "yes" ]; then
+    eval "${_resolvcmd}"
+  else
+    printf "${COLOUR_SET_B}Resolver commands =>${COLOUR_END}\n"
+    echo "${_resolvcmd}"
   fi
 
   # Set MAC address if using dhcp
   if [ "${_addr}" = "dhcp" -a "${_vnet}" = "eb" ]; then
-    echo "ifconfig epair${_id}b ether ${_macaddr}" > "${_path}/etc/start_if.epair${_id}b"
-    sysrc -q -f "${_path}/etc/rc.conf" ifconfig_epair${_id}b="SYNCDHCP" > /dev/null 2>&1
+    _netcmd=$(cat <<EOF
+  echo "ifconfig epair${_id}b ether ${_macaddr}" > "${_path}/etc/start_if.epair${_id}b"
+  sysrc -q -f "${_path}/etc/rc.conf" ifconfig_epair${_id}b="SYNCDHCP"
+EOF
+)
   # Otherwise use the provided address
   elif [ "${_vnet}" = "eb" ]; then
+    _netcmd=$(cat <<EOF
+  sysrc -q -f "${_path}/etc/rc.conf" ifconfig_epair${_id}b="inet ${_addr} netmask ${_netmask} up"
+  sysrc -q -f "${_path}/etc/rc.conf" defaultrouter="${_gw}"
+EOF
+)
+  fi
+  if [ "${_dry_run}" != "yes" ]; then
     > /dev/null 2>&1 \
-      sysrc -q -f "${_path}/etc/rc.conf" ifconfig_epair${_id}b="inet ${_addr} netmask ${_netmask} up"
-    > /dev/null 2>&1 \
-      sysrc -q -f "${_path}/etc/rc.conf" defaultrouter="${_gw}"
+    eval "${_netcmd}"
+  else
+    printf "${COLOUR_SET_B}Network setup commands =>${COLOUR_END}\n"
+    echo "${_netcmd}"
   fi
 
   # Set silent if required
   if [ ! -z ${_silent} ]; then
-    sysrc -q -f "${_path}"/etc/rc.conf cron_enable="NO" \
-      sendmail_enable="NONE" syslogd_flags="-ss"        \
-      > /dev/null 2>&1
+    _sysrcncmd=$(cat <<EOF
+  sysrc -q -f "${_path}"/etc/rc.conf cron_enable="NO"
+EOF
+)
+  fi
+  # ALWAYS disable sendmail and secure syslogd
+  _sysrccmd=$(cat <<EOF
+  sysrc -q -f "${_path}"/etc/rc.conf sendmail_enable="NONE" syslogd_flags="-ss"
+EOF
+)
+  if [ "${_dry_run}" != "yes" ]; then
+    > /dev/null 2>&1 \
+    eval "${_sysrcncmd}"
+    > /dev/null 2>&1 \
+    eval "${_sysrccmd}"
+  else
+    printf "${COLOUR_SET_B}Post-Installation =>${COLOUR_END}\n"
+    echo "${_sysrccmd}"
+    echo "${_sysrcncmd}"
   fi
 
-  sysrc -q jail_list+="${_name}" > /dev/null 2>&1
-  if !(jail::start ${_name} >/dev/null 2>&1); then
-    jail::exception::create
+
+
+  if [ "${_dry_run}" != "yes" ]; then
+    >/dev/null 2>&1 \
+    jail::start ${_name}
+    >/dev/null 2>&1 \
+    jls -j ${_name} || (printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n" && jail::exception::create )
+    printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"
   fi
-  [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
-               || (printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n" && return 1)
 }
 
 jail::console() {
diff --git a/lib/jailer-init b/lib/jailer-init
--- a/lib/jailer-init
+++ b/lib/jailer-init
@@ -1,39 +1,47 @@
 #!/bin/sh
 
+init::zfs::info(){
+  printf "${COLOUR_SET_B}Will create\n"
+  printf "${COLOUR_SET_M}dataset:${COLOUR_SET_C} $_dataset\n"
+  printf "${COLOUR_SET_M}mount point:${COLOUR_SET_C} ${_mpoint:-unknown}${COLOUR_END}\n"
+}
+
+init::zfs(){
+  printf "${COLOUR_SET_B}Creating ZFS dataset "
+  printf "${COLOUR_SET_C}$_dataset ${COLOUR_SET_B}"
+  printf "with the mount point ${COLOUR_SET_C}${_mpoint:-unknown}${COLOUR_END}: "
+
+  if ! eval "${_zcmd}" > /dev/null 2>&1 ; then
+    printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
+    util::err "Run this command to figure out why ZFS failed:\n $_zcmd"
+  else
+    printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"
+  fi
+}
+
 init::init(){
   local _dataset _initialised _mpoint _nodef _rcval _zcmd _zpool _zpool_no
+  local _yes
 
   shift
-  while getopts d:m:nz: _opt; do
+  while getopts d:m:nyz: _opt; do
     case ${_opt} in
       d)  _dataset="${OPTARG}" && opt_d=true ;;
       m)  _mpoint="${OPTARG}"                ;;
       n)  _nodef=true                        ;;
+      y)  _yes=true                          ;;
       z)  _zpool="${OPTARG}"   && opt_z=true ;;
     esac
   done
   shift $((OPTIND - 1))
 
+  [ "${1}" = "help" ] && man jailer-init && exit
   # XXX: It needs to be improved!
   # Check if jailer is already initialised
   ${_initialised:=false} # Assume it is not
   _rcval=$(sysrc -nq jailer_dir)
   [ ${#_rcval} -ne 0 ] && _initialised=true
 
-  # XXX: To be removed soon!
-  # Regardless of the following sanity checks etc. check if the patch
-  # for jail.conf.d is already applied
-  grep "jail_conf_dir" /etc/rc.d/jail >/dev/null 2>&1
-  if [ $? -ne 0 ]; then
-    printf "Patching jail service for jail.conf.d support: "
-    cp -v /etc/rc.d/jail /etc/rc.d/jail.origin && cp -v ${LIB}/init/jail /etc/rc.d/jail
-    if [ $? -eq 0 ]; then
-      printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"
-    else
-      printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
-      util::warn "Could not patch rc.d/jail, you need to take care of it manually"
-    fi
-  fi
   # If jailer is initialised beforehand, inform the user and exit
   if $_initialised; then
     util::err "Jailer seems to be already initialised (manually, perhaps?)"
@@ -67,26 +75,47 @@ init::init(){
     util::err "Only one of -z or -d can be provided"
   fi
 
-  # Enable the jail service first
-  printf "Enable the jail service first: "
-  service jail enable > /dev/null 2>&1
-  [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
-               || printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
-
-  # Initialise the world (main section, if reached)
-  printf "Setting jailer_dir in rc.conf: "
-  sysrc jailer_dir="zfs:$_dataset" > /dev/null 2>&1
-  [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
-               || printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
-
   if [ $_mpoint ]; then
     _zcmd="zfs create -o mountpoint=$_mpoint $_dataset"
   else
     _zcmd="zfs create $_dataset"
   fi
-  printf "Creating ZFS dataset $_dataset with the mount point ${_mpoint:-unknown}: "
-  $_zcmd > /dev/null 2>&1
-  [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"     \
-               || (printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n" &&
-                   util::warn "Run this command to figure out why ZFS failed: $_zcmd")
+
+  ${_yes:=false}
+  if ! ${_yes}; then
+    init::zfs::info
+    read -p "OK? (y/N) " _yes
+    if [ "${_yes}" = "y" -o "${_yes}" = "yes" ]; then
+      init::zfs
+    else
+      exit 0
+    fi
+  else
+    init::zfs
+  fi
+
+  # Enable the jail service first
+  printf "${COLOUR_SET_B}Enabling the jail service${COLOUR_END}: "
+  service jail enable > /dev/null 2>&1
+  [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
+               || printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
+
+  # Initialise the world (main section, if reached)
+  printf "${COLOUR_SET_B}Setting jailer_dir in rc.conf${COLOUR_END}: "
+  sysrc jailer_dir="zfs:$_dataset" > /dev/null 2>&1
+  [ $? -eq 0 ] && printf "${COLOUR_SET_G}Done!${COLOUR_END}\n" \
+               || printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
+
+  # Apply illuria's patches
+  grep "jail_conf_dir" /etc/rc.d/jail >/dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    printf "${COLOUR_SET_B}Patching jail service for jail.conf.d support${COLOUR_END}: "
+    cp /etc/rc.d/jail /etc/rc.d/jail.origin && cp ${LIB}/init/jail /etc/rc.d/jail
+    if [ $? -eq 0 ]; then
+      printf "${COLOUR_SET_G}Done!${COLOUR_END}\n"
+    else
+      printf "${COLOUR_SET_R}Failed!${COLOUR_END}\n"
+      util::warn "Could not patch rc.d/jail, you need to take care of it manually"
+    fi
+  fi
 }
diff --git a/lib/jailer-util b/lib/jailer-util
--- a/lib/jailer-util
+++ b/lib/jailer-util
@@ -1,8 +1,12 @@
 #!/bin/sh
 
 util::err() {
-  echo "${progname}: ERROR: $1" >&2
+  printf "\n${progname}: ${COLOUR_SET_R}ERROR: $1 ${COLOUR_END}\n" >&2
   exit 1
+}
+
+util::warn() {
+  printf "\n${COLOUR_SET_Y}WARN:${COLOUR_END} $1\n" >&2
 }
 
 util::tbd() {
@@ -20,7 +24,8 @@ Usage: jailer ...
     image list [version]
     image list remote
     image use [version]
-    create [-r version | -s snap] [-n] [-t eb|ng] [-b bridge|interface] [-d domain] [-g gateway -m netmask] [-a addr] [name]
+    create  [-D] [-r version | -s snap] [-n] [-d domain]
+            [-b bridge] [-t eb|ng] [-g gateway -m netmask] [-a addr] [name]
     destroy name
     list
     start [name ...]
@@ -41,6 +46,4 @@ util::version(){
   printf "v%s\nr%s\n" ${VERSION} ${VERSION_INT}
 }
 
-util::warn() {
-  echo "WARN: $1" >&2
-}
+
